name: mqtt-stress
services:
  mqtt-stress-vxmq:
    image: "jpforevers/vxmq:latest"
    container_name: mqtt-stress-vxmq
    restart: always
    ports:
      - "1883:1883"
      - "8060:8060"
      - "10022:10022"
    networks:
      - mqtt-stress
      
  mqtt-stress-mochi:
    image: "mochimqtt/server:latest"
    container_name: mqtt-stress-mochi
    restart: always
    ports:
      - "2883:1883"
      - "1882:1882"
      - "1880:1880"
    volumes:
      - ./mochi-config.yaml:/config.yaml
    networks:
      - mqtt-stress

  mqtt-stress-emqx:
    image: "emqx:latest"
    container_name: mqtt-stress-emqx
    restart: always
    ports:
      - "3883:1883"
      - "8083:8083"
      - "8084:8084"      
      - "8883:8883"      
      - "18083:18083"
    networks:
      - mqtt-stress
      
  mqtt-stress-mosquitto:
    image: "eclipse-mosquitto:latest"
    container_name: mqtt-stress-mosquitto
    restart: always
    ports:
      - "4883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf    
    networks:
      - mqtt-stress      

  mqtt-stress-hivemq:
    image: "hivemq/hivemq4:latest"
    container_name: mqtt-stress-hivemq
    restart: always
    ports:
      - "5883:1883"
      - "8080:8080"
    networks:
      - mqtt-stress      

  mqtt-stress-rmqtt:
    image: "rmqtt/rmqtt:latest"
    container_name: mqtt-stress-rmqtt
    restart: always
    ports:
      - "6883:1883"
    networks:
      - mqtt-stress          
    
  mqtt-stress-bifromq:
    mage: "bifromq/bifromq:latest"
    container_name: mqtt-stress-bifromq
    restart: always
    ports:
      - "7883:1883"
    networks:
      - mqtt-stress    
networks:
  mqtt-stress:

