name: mqtt-stress
services:
  mqtt-stress-vxmq:
    image: "jpforevers/vxmq:latest"
    container_name: mqtt-stress-vxmq
    restart: always
    ports:
      - "1883:1883"
    networks:
      - mqtt-stress
    mem_limit: 2048m 
      
  mqtt-stress-mochi:
    image: "mochimqtt/server:latest"
    container_name: mqtt-stress-mochi
    restart: always
    ports:
      - "2883:1883"
    volumes:
      - ./mochi-config.yaml:/config.yaml
    networks:
      - mqtt-stress
    mem_limit: 2048m  

  mqtt-stress-emqx:
    image: "emqx:latest"
    container_name: mqtt-stress-emqx
    restart: always
    ports:
      - "3883:1883"
    networks:
      - mqtt-stress
    mem_limit: 2048m  
      
  mqtt-stress-mosquitto:
    image: "eclipse-mosquitto:latest"
    container_name: mqtt-stress-mosquitto
    restart: always
    ports:
      - "4883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf    
    networks:
      - mqtt-stress
    mem_limit: 2048m      

#  mqtt-stress-hivemq:
#    image: "hivemq/hivemq4:latest"
#    container_name: mqtt-stress-hivemq
#    restart: always
#    ports:
#      - "5883:1883"
#    networks:
#      - mqtt-stress
#    mem_limit: 2048m

#  mqtt-stress-rmqtt:
#    image: "rmqtt/rmqtt:latest"
#    container_name: mqtt-stress-rmqtt
#    restart: always
#    ports:
#      - "6883:1883"
#    networks:
#      - mqtt-stress
#    mem_limit: 2048m
    
  mqtt-stress-bifromq:
    image: "bifromq/bifromq:latest"
    container_name: mqtt-stress-bifromq
    restart: always
    ports:
      - "7883:1883"
    networks:
      - mqtt-stress  
    mem_limit: 2048m
    
  mqtt-stress-vxmq-snapshot:
    image: "jpforevers/vxmq:999-SNAPSHOT"
    container_name: mqtt-stress-vxmq-snapshot
    restart: always
    ports:
      - "8883:1883"
    networks:
      - mqtt-stress
    mem_limit: 2048m   
        
networks:
  mqtt-stress:

